// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxZWMqW74TQtMVlpy2nJ282nhLOwCZ82Y',
    appId: '1:930447725105:web:6b412e1b980e798dc7bb10',
    messagingSenderId: '930447725105',
    projectId: 'kyusung-nomad-tiktok-clo-bf877',
    authDomain: 'kyusung-nomad-tiktok-clo-bf877.firebaseapp.com',
    storageBucket: 'kyusung-nomad-tiktok-clo-bf877.appspot.com',
    measurementId: 'G-03XSQG92GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR8kDAjEDyt_JTzg3ONnYXqbJ2alFqCbc',
    appId: '1:930447725105:android:0926db7b49cb60cdc7bb10',
    messagingSenderId: '930447725105',
    projectId: 'kyusung-nomad-tiktok-clo-bf877',
    storageBucket: 'kyusung-nomad-tiktok-clo-bf877.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD16MyfHzSQtCXmBd9nK2TTav-UPJsMzA',
    appId: '1:930447725105:ios:67d93a6fc6ecc61bc7bb10',
    messagingSenderId: '930447725105',
    projectId: 'kyusung-nomad-tiktok-clo-bf877',
    storageBucket: 'kyusung-nomad-tiktok-clo-bf877.appspot.com',
    iosBundleId: 'kr.leekyusung.tiktokClone',
  );

}